### ISSUE TITLE
Hi，

### ISSUE THREAD

**Issue by Damilytutu** [SBoulanger/blazepalm#2]

**Comment by Damilytutu** [comment]
Hi, can you tell me how to get the anchors.csv file? Thank you so much !

**Comment by SBoulanger** [comment]
The anchors.csv file should be in the base directory of this repo. https://github.com/SBoulanger/blazepalm/blob/master/anchors.csv

**Comment by Damilytutu** [comment]
Hi, I know you give the anchors.csv in the repo, can you tell me how do you calculate the anchors.csv according to the source from mediapipe? Thank you so much !

**Comment by SBoulanger** [comment]
Hey @Damilytutu , I see! Inside the media pipe source there is a ssd-anchor [generator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/ssd_anchors_calculator.cc). @wolterlw extracted this and created a cpp script you can use to generate a specific anchors.csv file. This [issue](https://github.com/wolterlw/hand_tracking/issues/3) explains the same thing. You should check out his hand_tracking repo as well!

**Comment by Damilytutu** [comment]
Thank you so much ! I got it. And I have another problem. The value of anchors of column three and four in anchors.csv is 1, which is different from the anchors of SSD. Do you know how to construct the true boxes (the dimension is [num_priors, 4] like SSD) using anchors.csv to calculate the loss in the training phase? Thank you so much !

**Comment by SBoulanger** [comment]
Column 3 and 4 are for width and height. They are 1 in our case because this model only has square anchors.

**Comment by SBoulanger** [comment]
You shouldn't construct the true boxes from the priors when calculating the loss. Simply use something like MeanSquaredError(L2/MSE) between the target and your prediction to get the loss value.
