### ISSUE TITLE
Network Structure

### ISSUE THREAD

**Issue by wyp19930313** [SBoulanger/blazepalm#4]
Google's [mediapipe](https://github.com/google/mediapipe) only provides [tflite](https://github.com/google/mediapipe/tree/master/mediapipe/models) files. How do you get the network structure? Hope to get your help, thank you

**Comment by wyp19930313** [comment]
I also want to get the network structure of [hand_landmark.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/models/hand_landmark.tflite), so that I can use this network structure to train my own data set, I hope to get your help, thank you

**Comment by SBoulanger** [comment]
https://github.com/lutzroeder/netron Netron is a good tool that can help you visualize the network structure and reproduce it
