### ISSUE TITLE
what does the anchor file mean?

### ISSUE THREAD

**Issue by wyp19930313** [SBoulanger/blazepalm#5]
I read the SSD paper, but I still don't understand what the numbers in the anchor file mean. From your code, I know that the first two columns of anchor represent the predicted target center point, but the last two columns are always 1. I don't know what they mean, hope to get your help, thank you

**Comment by SBoulanger** [comment]
The last two columns are the aspect ratio for height and width. We only have square boxes in this palm detection case, that is why it is 1:1. For SSD that is not the case because many non-palm objects have non-square aspect ratios.
