### ISSUE TITLE
How to transform tflite weights to npy

### ISSUE THREAD

**Issue by xuchengggg** [SBoulanger/blazepalm#7]
Hi, thank you for your wonderful work, I'm curious about how did you transform tflite weights to npy? And, when I test your model and palm_detection tflite model with same input image, there is a little difference between outputs, is there any changes or something.

**Comment by SBoulanger** [comment]
Embarrassingly enough, I manually extracted the weights with Netron. https://github.com/lutzroeder/netron

**Comment by SBoulanger** [comment]
I would not doubt there are some areas with errors. The extent of my validation for this repo was an eyeball test using a camera stream.

**Comment by xuchengggg** [comment]
Lol, I used 
```
inter_palm = tf.lite.Interpreter(model_path)
inter_palm.allocate_tensors()
weights = inter_palm.get_tensor(i)
np.save(weight_path, weights)
```
to store the weights from tflite model.

**Comment by xuchengggg** [comment]
I checked your model structure and some of weights,  and did not find any error. But I trust there must be some weights were loaded by mistake,  since the outputs of your model and original tflite model are not same, though the difference is small which may be the reason why your model can still output pretty good result.  
I reconstructed the model and load the weights, finally I got the same output with original tflite model.  Still thank you so much for providing an idea to construct the tf model from tflite model. Really appreciate for your work!!

**Comment by Junwen-Huang** [comment]
> I checked your model structure and some of weights, and did not find any error. But I trust there must be some weights were loaded by mistake, since the outputs of your model and original tflite model are not same, though the difference is small which may be the reason why your model can still output pretty good result.
> I reconstructed the model and load the weights, finally I got the same output with original tflite model. Still thank you so much for providing an idea to construct the tf model from tflite model. Really appreciate for your work!!

Is your code available? Actually I find some trouble when postprocessing output of the model and try to verify whether it is caused by wrong weights.

**Comment by xuchengggg** [comment]
您指哪方面的错误呢？ 其实主要就是先搭建正向的模型，然后每层卷积层的命名注意点，保证跟从tflite模型中把weight提取出来保存的名字相同（并不是说完全一样，比如说卷积层是resipool_1_dconv, 权重的名字保存为resipool_1_dconv_w.npy），这样可以保证在导入的时候用代码直接导入。我提取tflite模型的权重的时候基本上是手动的，因为tflite模型的权重用get_tensor提取的时候，会包含一些中间过程的变量（不一定按顺序的），比较难直接用代码将所有的权重一次性导出保存。

**Comment by Junwen-Huang** [comment]
> 您指哪方面的错误呢？ 其实主要就是先搭建正向的模型，然后每层卷积层的命名注意点，保证跟从tflite模型中把weight提取出来保存的名字相同（并不是说完全一样，比如说卷积层是resipool_1_dconv, 权重的名字保存为resipool_1_dconv_w.npy），这样可以保证在导入的时候用代码直接导入。我提取tflite模型的权重的时候基本上是手动的，因为tflite模型的权重用get_tensor提取的时候，会包含一些中间过程的变量（不一定按顺序的），比较难直接用代码将所有的权重一次性导出保存。

我是在跑test.py时发现有很多误检的框，看到了这个issue以后怀疑权重加载有问题。但按您的说法似乎原代码中的加载方法是无误的？

**Comment by xuchengggg** [comment]
我感觉他可能在保存权重的时候有错误把，但是我也没有找出来到底哪里错误，但是我用同样的图片输入他的网络和原来tflite的输出对比是有差别的，所以我觉得一定是哪里有错误的。我自己还原的模型的输出和tflite的就是完全一样的。不过他这个应该效果也不会太差的，您可以试一下将图片输入到tflite中看一下输出结果，有可能是预处理这些地方做错了，或者本身网络的输出就比较差

**Comment by Junwen-Huang** [comment]
> 我感觉他可能在保存权重的时候有错误把，但是我也没有找出来到底哪里错误，但是我用同样的图片输入他的网络和原来tflite的输出对比是有差别的，所以我觉得一定是哪里有错误的。我自己还原的模型的输出和tflite的就是完全一样的。不过他这个应该效果也不会太差的，您可以试一下将图片输入到tflite中看一下输出结果，有可能是预处理这些地方做错了，或者本身网络的输出就比较差

好的，感谢您的回复~
